{"name": "[Title] 验证正确的用户名和密码能否成功登录", "status": "failed", "statusDetails": {"message": "AssertionError: assert False", "trace": "self = <test_5allure_报告设置.test_allure04.TestLogin object at 0x000001FBAF189B00>\n\n    def test_login01(self):\n        allure.dynamic.story(\"[story] 登录用例01\")  # 测试用例\n        allure.dynamic.title('[Title] 验证正确的用户名和密码能否成功登录')\n    \n>       assert False\nE       assert False\n\ntest_allure04.py:20: AssertionError"}, "start": 1663490185920, "stop": 1663490185921, "uuid": "f94dd6f5-7910-4964-b0e6-cdc34f06ad6f", "historyId": "493ec5dffad67c325d2777c632c6b9ef", "testCaseId": "579f3bbe6b6639e4b058a4da42cb57f5", "fullName": "test_allure04.TestLogin#test_login01", "labels": [{"name": "story", "value": "[story] 登录用例01"}, {"name": "epic", "value": "[epic] 淘宝电商系统测试"}, {"name": "suite", "value": "test_allure04"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-1OCD62H"}, {"name": "thread", "value": "8676-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_allure04"}]}