{"name": "用户名错误的场景", "status": "passed", "description": "我们的第一个登录小程序", "attachments": [{"name": "接口地址", "source": "6ef1d958-e731-4e3e-bf5a-fd8c0789a2f5-attachment.attach"}, {"name": "接口参数", "source": "b2ac9f57-65ab-4cd1-891d-89bc3bd4635e-attachment.attach"}, {"name": "响应结果", "source": "6daa4b51-0211-4a95-8ceb-336a7fcae0b5-attachment.attach"}, {"name": "log", "source": "e9e5d509-75b7-49e8-bbfc-91e2afc92fa6-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "e9622d4d-ee4b-446f-974c-ad3a5231f847-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "case", "value": "<day15.test_excel_data.excel_test02.CaseData object at 0x0000028D2F186C88>"}], "start": 1660463253545, "stop": 1660463253625, "uuid": "3f6c067b-580c-448a-a288-6a535b98b000", "historyId": "1bb4d0d4dee87ef9721af1acce06bbdb", "testCaseId": "b62a022e3184708d2d40012e446c9b1d", "fullName": "test_login.TestLogin#test_login", "labels": [{"name": "story", "value": "登录模块的子模块"}, {"name": "severity", "value": "critical"}, {"name": "feature", "value": "登录模块"}, {"name": "suite", "value": "test_login"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "DESKTOP-31HM1IE"}, {"name": "thread", "value": "9324-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login"}]}